### ISSUE TITLE
pmol to µM calculation not working

### ISSUE THREAD

**Issue by LipidomicsHeidelberg** [luechtian/ShinyLipidcountr#2]
![grafik](https://user-images.githubusercontent.com/112397099/187199047-dc9267cd-b0d3-4085-87c8-7c00403e55cd.png)
Hallo, 
der letzte Berechnungsbutton funktioniert in der alpha 2 nicht. Das Workbook hat dann keine Daten.

**Comment by luechtian** [comment]
Sehr cool, dass du GitHub benutzt. Jetzt müssen die Issues nur noch in der richtigen Repo geöffnet werden :)

https://github.com/luechtian/ShinyLipidcountr/issues

**Comment by luechtian** [comment]
Schick mir mal deine textfiles + metadata. Mit meinen Files funktioniert alles.

Edit: Ich sehe gerade, dass in der Spalte "sample_input" keine Werte sind. Ich gehe davon aus, dass du die Sample names im Metadaten-file nicht aktualisiert hast. Sample01 versus Sample 1 zB.

**Comment by LipidomicsHeidelberg** [comment]
Die anderen 3 Berechnungen macht er. Dachte ich hätte alle samples richtig benannt.
[Daten_Caroline_Pabst.zip](https://github.com/luechtian/lipidcountr/files/9444818/Daten_Caroline_Pabst.zip)


edit: Ich habe die sample Namen mit kopieren und ersetzen geändert, darum hieß mein sample input sample0 input. Hat sich geklärt bei näherem Hinsehen

**Comment by luechtian** [comment]
![image](https://user-images.githubusercontent.com/51409126/187214712-8e4575c3-2356-4229-b0f9-51b8c54eda1a.png)
"sample input" muss da stehen, auch nicht in Großbuchstaben.

So kann er nicht mehr die Probenvolumina zuweisen.

**Comment by luechtian** [comment]
[Metadata_CarolinePabst_corrected.csv](https://github.com/luechtian/lipidcountr/files/9445071/Metadata_CarolinePabst_corrected.csv)

**Comment by luechtian** [comment]
Now there is a control in check_raw_meta() for the meta-dataframe. It is mandatory, that the first three elements of the column 'class' are called 'group', 'blank' and 'sample input'. check_raw_meta() is triggered by 'Add metadata'-button.
![image](https://user-images.githubusercontent.com/51409126/187226899-2abb5771-f28d-4a14-8b6a-918bbfb5a06a.png)
